baseURL = ""
title = "GGC | Police Roleplay Regelwerk"
theme = "book"
disablePathToLower = true
enableGitInfo = false
themesDir = "themes"
publishDir = "public"
disableLanguages = ["ru", "zh"]

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 1

[languages.en]
languageName = "English"
contentDir = "content"
weight = 1

[languages.ru]
languageName = "Russian"
contentDir = "content.ru"
weight = 2

[languages.zh]
languageName = "Chinese"
contentDir = "content.zh"
weight = 3

[[menu.after]]
name = "Forum"
url = "https://ggc.lol/"
weight = 10

[[menu.after]]
name = "Impressum"
url = "https://ggc.lol/index.php?legal-notice/"
weight = 20

[params]
BookTheme = "dark"
BookToC = false
BookSection = "docs"
BookRepo = "https://github.com/alex-shpak/hugo-book"
BookEditPath = "edit/master/exampleSite"
BookDateFormat = "January 2, 2006"
BookSearch = true
BookComments = false
BookPortableLinks = true
BookServiceWorker = true
